language: php
php:
  - '5.6'
  - '7.0'
  - hhvm
  - nightly
before_script:
  - composer self-update
  - composer install -n
  - composer require -N satooshi/php-coveralls:dev-master
script:
  - ./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml
after_script:
  - php vendor/bin/coveralls -v